### PR TITLE
Update Hungarian translation

### PR DESCRIPTION
**Pull request by cooljeanius**
So, @kele17 sent me a new `hu.po` file by email, for issue #10... it doesn't look quite right, though; @celerini can you review please?

### CODE REVIEW

**Comment by celerini** [comment]
Thanks for an interesting task.

What I found out so far:

- the biggest problem is, that both the new file and the first @kele17 attempt are cut after message number 1389, thus despite @kele17 efforts, there are 1697 missing trailing messages in kele17's hu.po files

- the new file is now correctly wrapped after 79th character - it's good, but line endings are set to CRLF (Windows), which is bad

- there are still errors in messages with a context, as I already stated in #91

- Poedit shows me :warning: for various minor errors - missing or superfluous spaces, differences in terminal punctuation...

So from my point of view this PR should be dropped.

To help @kele17 and save his efforts I repaired his hu.po files:
- [his first attempt repaired](https://github.com/celerini/A_New_Order/commit/cb40bc6a9d53fe2552c5e0280f69f93a6d1e45a6) - 2617 translated messages, 219 fuzzy translations, 250 untranslated messages
- [his second attempt repaired](https://github.com/celerini/A_New_Order/commit/457062da8c26d42e31b8f9e5ecfdce06daea7106) - 2621 translated messages, 215 fuzzy translations, 250 untranslated messages
- the second [looks slightly improved](https://github.com/celerini/A_New_Order/compare/cb40bc6..457062d#diff-fb1b704ff9b61492139575127e7b1b48cfb550ddebace3070b3445640f2cd37d) (click Load diff for hu.po), but kele17 should decide about it

The repaired files are still far from merging, thus here are my recommendations to @kele17:
- choose one of my repaired files if you don't have any better
- download **raw** file: three dots icon -> View file -> Raw, Ctrl+S (save)
- open this hu.po file in Poedit, verify in bottom status line that there are 3086 messages altogether
- set LF line endings: Edit -> Preferences -> Advanced -> Line endings: Unix (recommended)
- [translate messages with a context correctly](https://wiki.wesnoth.org/GettextForTranslators#FAQ)
- resolve every message with :warning: in Poedit
- do not translate further, instead send us your fixed hu.po file, so I can easily check if we understand each other and your work can be merged

**Comment by cooljeanius** [comment]
ok, @kele17 has sent a new pofile... this one looks like it now diffs properly, at least; I haven't reviewed the whole thing... (will probably want to squash when merging)

**Comment by cooljeanius** [comment]
> ok, @kele17 has sent a new pofile... this one looks like it now diffs properly, at least; I haven't reviewed the whole thing... (will probably want to squash when merging)

ok so yeah I've looked over the rest of it now and it looks a lot better; I can't comment as to the correctness of the words, but I think I'll merge it soon, unless @celerini has something to say within 24 hours.

**Comment by celerini** [comment]
All major errors were fixed, thanks.

There are still messages with :warning: in Poedit - some false positives (those with a context), some may be intended (I would appreciate a translator comment in such cases) and some may be real errors, which should be fixed. But it can be done later.

In my opinion this PR can be merged now. Squashing looks reasonable in this case.

**Comment by kele17** [comment]
I started from the beginning. Get the repaired file, and make some new translated string, just to see the errors. Fuzzy string and untranslated strings will bw translated soon, maybe a week. I will send it to Eric, if it is ready. 
Sorry for inconvenience, i was not directly connected to i18n process, now was this new for me. And have a technical problem with my notebook too, it was in service for a month. Now it seems everything ok. so i will send the whole revised file soon.

**Comment by cooljeanius** [comment]
> All major errors were fixed, thanks.
> 
> There are still messages with ⚠️ in Poedit - some false positives (those with a context), some may be intended (I would appreciate a translator comment in such cases) and some may be real errors, which should be fixed. But it can be done later.
> 
> In my opinion this PR can be merged now. Squashing looks reasonable in this case.

OK, merging and squashing now, then

**Pull request merged**
