### PR TITLE
Translation updating branch

### PR DESCRIPTION
**Pull request by cooljeanius**
This PR is to get the ball rolling on updating translations as per #10. So far all it does is to use `msgunfmt` to convert mofiles back into pofiles, but I also plan on playing with the rest of the gettext tools to see what else they can do that might be useful. I'm not sure why the `cs.po` from #41 and #48 isn't appearing in my branch; @celerini and @MultiSeptim any ideas? Also now that I can actually see all of the headers for all the translations, including the email addresses, I'm wondering if it would make sense to send out a mass email to all of the addresses listed to let them know that there's new translation to be done?

### CODE REVIEW

**Comment by celerini** [comment]
I placed [cs.po under the po/ directory](https://github.com/nemaara/A_New_Order/tree/master/po). I thought that this is the right place. Maybe I was wrong.

You already have our cs.po in [your A_New_Order-1 repo](https://github.com/cooljeanius/A_New_Order-1/tree/master/po).

Our cs.po is more recent - POT updated and with @MultiSeptim's translations. Please try to preserve it.

**Comment by cooljeanius** [comment]
.@nemaara do you know what the proper location for them is? i.e., where the game will actually load them?

**Comment by celerini** [comment]
There is an information about [generating the .pot and .po files for UMC
](https://wiki.wesnoth.org/GettextForWesnothDevelopers#Generating_the_.pot_and_.po_files_for_UMC)

So our cs.po should be in translations/wesnoth-A_New_Order/cs.po.

My question is why are the redundant, commentless binary .mo files stored in this repo? They can be generated right before uploading the add-on and excluded from git.

**Comment by cooljeanius** [comment]
> My question is why are the redundant, commentless binary .mo files stored in this repo? They can be generated right before uploading the add-on and excluded from git.

You'd have to ask either @nemaara or szopen; they've been here since before I started contributing to it

**Comment by nemaara** [comment]
Tbh I don't know how translations really work, they were there when I first got the addon from szopen.

**Comment by celerini** [comment]
Eric, please close this PR.

The location of your .po files is wrong as I stated in #59 and msgunfmt is not ideal, because there is 
loss of information (header, comments). And there are lot of other languages in [WesCamp A New Order 1.10](https://github.com/wescamp/A_New_Order-1.10/tree/master/po).

So, I hate promising, but I can check these translations, run POT update against them, verify, that they are actually translating the ANO add-on and prepare a new PR to include them all.

What do you think about that?

**Comment by cooljeanius** [comment]
> Eric, please close this PR.
> 
> The location of your .po files is wrong as I stated in #59 and msgunfmt is not ideal, because there is loss of information (header, comments). And there are lot of other languages in [WesCamp A New Order 1.10](https://github.com/wescamp/A_New_Order-1.10/tree/master/po).
> 
> So, I hate promising, but I can check these translations, run POT update against them, verify, that they are actually translating the ANO add-on and prepare a new PR to include them all.
> 
> What do you think about that?

Well ok, once you do all that, then I will close this PR.

**Comment by celerini** [comment]
I did something in #60, but I must apologize. There are many languages in WesCamp ANO 1.10, but most of them has 0% translated. The en_GB has 5%, but somebody had his own reason to not include it here, so I let it be.

And the .mo files in this repo are a little bit more recent than those in WesCamp ANO 1.10, so I used msgunfmt as you did. Sorry for delaying your work.

Mea culpa.

**Comment by cooljeanius** [comment]
So... what do I do with this PR then? Do I close it or not? I'm confused.

**Comment by celerini** [comment]
You can close it, #60 should be better.

**Comment by cooljeanius** [comment]
ok, closing

**Comment by antonino-arcudi** [comment]
Hi there,
I am available for the translation. I've received the mail.
Where are the po files?

**Comment by cooljeanius** [comment]
> Hi there, I am available for the translation. I've received the mail. Where are the po files?

po files are in translations/wesnoth-A_New_Order: https://github.com/nemaara/A_New_Order/tree/master/translations/wesnoth-A_New_Order
(also, we're using issue #10 for further collaboration on translations now)

**Pull request closed without merging**
