### PR TITLE
ES - Title and difficulty translated 

### PR DESCRIPTION
**Pull request by Toranks**
Being the first thing the player sees, it's the most important thing, so I send it since it's just a moment

### CODE REVIEW

**Comment by cooljeanius** [comment]
uh, it says it's too big to view the diff...

**Comment by cooljeanius** [comment]
Did you change the line endings or something? Viewing it locally, it looks like the entire file got reformatted...

**Comment by Toranks** [comment]
Probably, I've edited it on poedit. Looking with winmerge it is seen that the type of line break has changed for example.
In any case, don't worry about it, Wesnoth reads it the same, poedit is one of the most used tools.

imagen

**Comment by cooljeanius** [comment]
If you go into Poedit's preferences, there ought to be an option for line ending style under "Advanced":
Screen Shot 2023-02-25 at 22 23 50

**Comment by Toranks** [comment]
I have exactly the same as you xD
imagen

**Comment by celerini** [comment]
@Toranks , you may have the same settings (Unix line endings), but I guess you did not use it when saving your es.po for this PR.

Please, drop this PR and create a new one, without non-standard line endings (without Carriage Returns), which polluted git with over 21k changes.

Or I can do it for you on my own.

**Comment by Toranks** [comment]
Done, see the changes again

**Comment by celerini** [comment]
Thank you, I am content with this.

@cooljeanius or @nemaara , can you please squash this PR to dispose all the back and forth changes?

**Review by cooljeanius — APPROVED** [review]

**Comment by cooljeanius** [comment]
> Thank you, I am content with this.
> 
> @cooljeanius or @nemaara , can you please squash this PR to dispose all the back and forth changes?

Done.

**Pull request merged**
