### PR TITLE
Make terrain in fall maps look more fall-like

### LINKED ISSUE #63: Use autumn terrain when applicable
Scenario 10, Siege of Haeltin, marks the start of winter. Everything before that is soon before it, so it should still be autumn. This can be confirmed by looking at `images/story_images/gawen_alone.png`, which has a background with fall colors in it. Any maps in the first 10 scenarios should be updated to use fall terrain when applicable, for example, with any deciduous forests.

### PR DESCRIPTION
**Pull request by cooljeanius**
Closes #63 
(hopefully; let's see if the action works...)

### CODE REVIEW

**Comment by cooljeanius** [comment]
Darn @macabeus it didn't work... help?

**Comment by cooljeanius** [comment]
@nemaara did you want me to try to fix the map diff thing so it runs on PRs in this repo properly, or should I just run the tool manually and then hand-upload the diff images, or should I just merge without doing either of those?

**Comment by macabeus** [comment]
@cooljeanius I think the easiest way to fix it is editing the GitHub Action to clone `wesnoth` repository (it won't need to clone the whole history, but only the latest commit) and run it from there.

The issue is because it depends on the images and `.cfg` files that aren't present here.

This approach isn't pretty, but I don't have a better idea now. I didn't make `map-diff` planning to run on the repositories.

**Comment by nemaara** [comment]
> @nemaara did you want me to try to fix the map diff thing so it runs on PRs in this repo properly, or should I just run the tool manually and then hand-upload the diff images, or should I just merge without doing either of those?

Doesn't matter to me, as long as nothing breaks in the release version.

**Comment by cooljeanius** [comment]
> @cooljeanius I think the easiest way to fix it is editing the GitHub Action to clone `wesnoth` repository (it won't need to clone the whole history, but only the latest commit) and run it from there.

Hm I'm kinda bad at git; can you remind me how to do that? Also, besides just restricting it to the latest commit, can we also restrict it to just the directories we need, instead of getting the whole repository?

**Comment by macabeus** [comment]
@cooljeanius Command to clone only the latest commit:
```
git clone --depth 1 git@github.com:wesnoth/wesnoth.git
```

About cloning just a directory, it can be done: https://stackoverflow.com/a/52269934/3440266
I never did it, but it seems to work.
You would need to clone the folders `./data/core`, `./images`, and `./utils/wesnoth-map-diff` (I hope not missing to mention a folder).

**Comment by cooljeanius** [comment]
> ./utils/wesnoth-map-diff

hm ok I'm trying this, and while the commands don't seem to error out on me or anything, they also don't result in anything getting actually checked out for me either...

**Comment by cooljeanius** [comment]
OK I think the latest results exposed a bug in the `wesnoth-map-diff` tool:
```
/home/runner/work/A_New_Order/A_New_Order/utils/wesnoth-map-diff/build/tilemap.js:59
        if (left[y][x].baseCode !== right[y][x].baseCode
                                                ^
TypeError: Cannot read properties of undefined (reading 'baseCode')
    at /home/runner/work/A_New_Order/A_New_Order/utils/wesnoth-map-diff/build/tilemap.js:59:49
    at walkthrough (/home/runner/work/A_New_Order/A_New_Order/utils/wesnoth-map-diff/build/tilemap.js:41:9)
    at Object.diff (/home/runner/work/A_New_Order/A_New_Order/utils/wesnoth-map-diff/build/tilemap.js:58:5)
    at paintTilemap (/home/runner/work/A_New_Order/A_New_Order/utils/wesnoth-map-diff/build/paint.js:79:21)
    at Jimp.<anonymous> (/home/runner/work/A_New_Order/A_New_Order/utils/wesnoth-map-diff/build/paint.js:84:9)
    at Timeout._onTimeout (/home/runner/work/A_New_Order/A_New_Order/utils/wesnoth-map-diff/node_modules/@jimp/core/dist/index.js:264:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Error: Process completed with exit code 1.
```
(discussed on Discord, but I forget how far back that was, so I'm putting it here, too)

**Comment by macabeus** [comment]
@cooljeanius Are these maps the same size?
`wesnoth-map-diff` won't work if one of the maps has different dimensions

**Comment by cooljeanius** [comment]
eyyy it worked! @nemaara check it out!

**Comment by cooljeanius** [comment]
oops looking at the diff output made me realize I missed a few tiles; let me fix that...

**Comment by cooljeanius** [comment]
oh cool so it looks like it edits the existing comment with the new diffs instead of posting a new comment; that's convenient

**Comment by macabeus** [comment]
Amazing!! It's working!!! 🎉 
Great job!

image

**Comment by cooljeanius** [comment]
> Amazing!! It's working!!! 🎉 Great job!

One thing I do find kinda confusing, though, is how in normal diff views, the old content is on the left and the new content is on the right, but here it's switched so the new content is on the left and the old content is on the right...

**Comment by macabeus** [comment]
@cooljeanius 
Try replacing
```
node ./build/index.js "./$map_filename" "../../$map_path" "./$diff_image"
```
with
```
node ./build/index.js "./$map_path" "../../$map_filename" "./$diff_image"
```

**Review by nemaara — APPROVED** [review]

**Pull request merged**
