### PR TITLE
Spanish translation 100% (except debug strings)

### LINKED ISSUE #111: Useless spanish translation
As I progress through the game the translation gets worse and worse, to the point of saying things that have nothing to do with it. I would recommend that in the next update you completely deactivate the translation except what I sent in my PR, waiting for it to be done correctly. It'll take a few months, but I'm almost done with Era of Magic. I also have to update the one for Eastern Invasion Revised to the latest version.

### PR DESCRIPTION
**Pull request by Toranks**
I send it in draft until it is really 100% to keep track of progress

Resolves #111 
Partially #10

### CODE REVIEW

**Comment by cooljeanius** [comment]
hm, apparently there's a conflict?

**Comment by Toranks** [comment]
> hm, apparently there's a conflict?

I don't understand what that means xD Obviously there are differences between master and my PR, that's what PR is all about! xD

**Comment by cooljeanius** [comment]
> > hm, apparently there's a conflict?
> 
> Yes, but I don't understand what that means xD Obviously there are differences between master and my PR, that's what PR is all about! xD

It's because this PR branched off at a different point; master has received new updates since you first created this branch which you need to merge back into this branch first. Specifically, 7c62567c9f23e8eae6cc6b8b6abdb7c4a7bffab8, 1a3798f7d42d124fbcfa9747b8d4db8ba290fc15, e33df5fca858fb78ead090c2b1bbc057bf317622, b449e9dd65e22eb9a017b6a6ebe855af5373183a, and 39617922008ce806b9eaea972245bbf5f16e8108 all also touched this file.

**Comment by Toranks** [comment]
Everything is already included, I guess it will be enough to force the PR by replacing the file.

**Comment by cooljeanius** [comment]
> Everything is already included, I guess it will be enough to force the PR by replacing the file.

@nemaara do we have a policy on using force-pushes to merge?

**Comment by cooljeanius** [comment]
looking at the translation file some more in Poedit, I'm noticing more source strings that I ought to touch up, but I don't want to create more work for you (at least not just yet), so I'll put that off until after our next release... copyediting is tracked in issue #5 anyways...

**Comment by Toranks** [comment]
At last!

**Comment by cooljeanius** [comment]
Hm, looks like GitHub doesn't present a "force-push" option for merging via the web UI; I'm going to figure out how to do this via the command line...

**Comment by Toranks** [comment]
I finally figured out how to fix conflicts. On Github Desktop: "Branch" > "Update from upstream/master" > Select on the files with conflict to use the current branch, not upstream/master branch.

**Comment by cooljeanius** [comment]
> I finally figured out how to fix conflicts. On Github Desktop: "Branch" > "Update from upstream/master" > Select on the files with conflict to use the current branch, not upstream/master branch.

ok cool, I'll squash and merge now

**Pull request merged**
