### PR TITLE
Fix invalid [kill] and Reumario joining on 09 Hired Swords

### PR DESCRIPTION
**Pull request by Toranks**
Also removed several redundant [command] tags to make it easier to read and avoid this type of error.
Maybe solves https://forums.wesnoth.org/viewtopic.php?p=682407#p682407 (NOT TESTED)

### CODE REVIEW

**Comment by cooljeanius** [comment]
> Maybe solves [forums.wesnoth.org/viewtopic.php?p=682407#p682407](https://forums.wesnoth.org/viewtopic.php?p=682407#p682407) (NOT TESTED)

Hm, I guess if the reporter from there won't test it, I can do so once I get back from Oregon...

**Comment by cooljeanius** [comment]
Uploading a savefile for the start of the scenario, in case anyone else would like to test: [ANO-Hired Swords.gz](https://github.com/nemaara/A_New_Order/files/12014464/ANO-Hired.Swords.gz)
(this is the same one I sent to @Toranks on Discord, but I figured I'd put it here as well)

**Comment by Toranks** [comment]
Tested 3 situations:
- I killed the other leader, offered to join my forces, he refused, and then did the same to Reumario.
- I killed the other leader, interrogated him, and Reumario joins us directly.
- I killed Reumario first, offered to join my forces, and he accepted.

In all three cases Rheumario joins correctly.

I leave here the same savegame but with GUI Debug Tools enabled, to facilitate testing.

[ANO-Hired Swords + GUI Debug Tools.gz](https://github.com/nemaara/A_New_Order/files/12016650/ANO-Hired.Swords.%2B.GUI.Debug.Tools.gz)

**Comment by cooljeanius** [comment]
> Tested 3 situations:
> 
>     * I killed the other leader, offered to join my forces, he refused, and then did the same to Reumario.
> 
>     * I killed the other leader, interrogated him, and Reumario joins us directly.
> 
>     * I killed Reumario first, offered to join my forces, and he accepted.
> 
> 
> In all three cases Rheumario joins correctly.

Ok, so that means it's probably ok, but let's get one more pair of eyes from @nemaara before merging...

**Review by cooljeanius — APPROVED** [review]

**Review by nemaara — APPROVED** [review]

**Pull request merged**
