### PR TITLE
Loyal overlay fixes

### PR DESCRIPTION
**Pull request by Toranks**
Lady Lorin is recovered just as it was left in the previous scenario, getting her id. It is unnecessary to make the same modifications.
I only send the scenarios that I have already verified that Lady Lorin retains her loyal and strong (on easy) traits, so as I progress in the campaign I will send the other fixes. This is part of the fix of #98

### CODE REVIEW

**Comment by cooljeanius** [comment]
> Lady Lorin is recovered just as it was left in the previous scenario, getting her id. It is unnecessary to make the same modifications. I only send the scenarios that I have already verified that Lady Lorin retains her loyal and strong (on easy) traits, so as I progress in the campaign I will send the other fixes. 

OK, maybe convert this into draft mode, then?

**Comment by Toranks** [comment]
Closed this:
https://github.com/nemaara/A_New_Order/pull/108
The changes explained there are made here, since they affect the same files and it is more convenient. All changes up to this comment are tested.

**Comment by cooljeanius** [comment]
@Toranks sorry I introduced some merge conflicts with #109, which has now been merged

**Comment by Toranks** [comment]
Tested here ^

**Comment by cooljeanius** [comment]
> I'm already on the last mission, I've done all possible side missions, and I haven't seen any more icon overlays, so it's ready to merge, if that's okay with you.

ok, let's get a review from @nemaara too first, though

**Comment by nemaara** [comment]
Wait it looks like you removed egallager's thing where he gave the STRONG trait on easy mode though.

**Comment by Toranks** [comment]
Oh, sorry. Restored.

**Review by nemaara — APPROVED** [review]

**Pull request merged**
